-- Geofencing: a radius per site + where each report was filed from.
ALTER TABLE "Site"
  ADD COLUMN IF NOT EXISTS "geofenceRadius" INTEGER;

ALTER TABLE "Report"
  ADD COLUMN IF NOT EXISTS "filedLat" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "filedLng" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "filedAccuracy" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "siteLat" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "siteLng" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "siteRadiusM" INTEGER,
  ADD COLUMN IF NOT EXISTS "geofenceStatus" TEXT,
  ADD COLUMN IF NOT EXISTS "geofenceDistanceM" INTEGER;
